### ISSUE TITLE
Refuses to install in 3.6

### ISSUE THREAD

**Issue by bfriesenvcc** [blackboard-open-source/moodle-tool_ally#33]
I'm in the middle of an upgrade and this is stalling everything.  I'm in an endless installation loop. I read that purging all cache may help, but I cannot even get to that screen. Any help would be appreciated. Thanks, in advance!

![Tool_Ally_error](https://user-images.githubusercontent.com/8193384/61807898-4224ae80-adef-11e9-873f-acda26932182.PNG)

**Comment by bfriesenvcc** [comment]
We have had to completely remove Ally from our Moodle instance in order to complete the upgrade. We're going to try to install the 3.5 version, once we're finished everything else and we've made a snapshot.

**Comment by cybernotic** [comment]
I have just tried to install ally on an install of Moodle 3.7, details below:
Enviroment:
moodle  3.7 (Build: 20190520) 
database mysql (5.6.36-enterprise-commercial-advanced-log) 
php version 7.1.0 
I received a similar error as the above (bfriesenvcc), but my error messaged occurred after I clicked 'Auto configure Ally web service :
![errmsg](https://user-images.githubusercontent.com/18535468/61878344-c149dd80-aee8-11e9-965c-24f67571f9a6.png)

I will look in to this but I just wanted to report this now to see if you can shed some light on this issue.

Regards
David

**Comment by bfriesenvcc** [comment]
Our IT guy ended up removing the tables, then we first installed the 3.5 version and then upgraded to the 3.6 version. Going directly to the 3.6 version didn't work, for some reason.

**Comment by dvdcastro** [comment]
Latest 3.6.5 version works for installing from scratch again.
