### ISSUE TITLE
Excessive memory usage by get get_section_number in course_component 

### ISSUE THREAD

**Issue by LoveBug** [blackboard-open-source/moodle-tool_ally#40]
Hi, This is in regard to the following section of code:

https://github.com/blackboard-open-source/moodle-tool_ally/blob/b4c506abcef0593c31d7f0e431e96f6e72e68d97/classes/componentsupport/course_component.php#L160-L167

We are finding that when run on a large enough (over 500 thousand course sections) Moodle instance that this function is causing excessive memory use, in my testing, over 300Megabytes which depending on the request can easily  exceed reasonable PHP memory limits. 

The function on a cursory inspection does not appear to be called often enough to justify the static cache so I have written a patch to remove the cache and replace it with a simple database query.
This may not be appropriate, so some guidance would be greatly appreciated.

**Comment by andrewrowatt-masseyuni** [comment]
@gthomas2 et al it would be great to get some advice on this patch.  Thanks.

**Comment by LoveBug** [comment]
Hi, I was going through my pull requests, and wondering if there was any potential for a follow up on this. On larger sites this issue can and does cause large problems as it can crash every course update, and potentially the entire site in some cases.

**Comment by dvdcastro** [comment]
This was resolved when #41 was merged.
