### ISSUE TITLE
Secret, Key, Launch URL, File updates URL and Client id fields

### ISSUE THREAD

**Issue by anleba512** [blackboard-open-source/moodle-tool_ally#43]
I have reviewed the links provided on the Moodle Plugin page and have sent messages to locate Secret, Key, Launch URL, File updates URL and Client id fields values mentioned as needed for installation.  Where might one find an Ally Representative?  

The Secret, Key, Launch URL, File updates URL and Client id fields should be populated with values provided to you by an Ally representative. You can contact an Ally representative online via the Ally  webpage https://www.blackboard.com/accessibility/blackboard-ally.aspx.

**Comment by merrill-oakland** [comment]
Ally is a paid service. You would need to contract with Blackboard to get it, and then you would have rep contacts.
